# Artist Rule
ARTIST_BONUS = 20
ARTIST_PENALTY = -50
ARTIST_WEIGHT = 2.0

# Album Rule
ALBUM_BONUS = 10
ALBUM_PENALTY = -20
ALBUM_WEIGHT = 1.0

# Randomness
RANDOM_MIN = 0
RANDOM_MAX = 100
RANDOM_WEIGHT = 1.0

# History
ARTIST_SPACING = 5
ALBUM_SPACING = 3